services:
  ctfd:
    image: ghcr.io/hexcore-labs/ctfd:main@sha256:9067252588a8a18393790dc935a6d739ccd14d3e0c53eaf7c6a70b3a0a487367
    pull_policy: always
    restart: always
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - CACHE_TYPE=redis
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      permissions:
        condition: service_completed_successfully
      redis:
        condition: service_started

  # TODO: CTFd 4.0 Migrate to named volumes. Users will likely need to manually migrate existing files
  permissions:
    image: alpine:3.23
    user: root
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    command: chown -R 1001:1001 /var/uploads /var/log/CTFd

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  api:
    image: ghcr.io/hexcore-labs/lockdown-api:main
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${LOCKDOWN_PORT:-4000}:${PORT:-4000}"
    env_file:
      - .env
    environment:
      - CTFD_URL=http://ctfd:8000

  redis:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data